version: "3.7"

networks:
  gateway:
    external: true

services:
  postgres:
    container_name: arklet_db
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - gateway

  arklet-minter:
    platform: linux/amd64
    container_name: arklet_minter
    restart: always
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./ark:/app/ark
      - ./ark_import:/app/ark_import
      - ./arklet:/app/arklet
    env_file:
      - .env
    environment:
      ARKLET_PORT: "8017"
    ports:
      - "127.0.0.1:8017:8017"
    networks:
      - gateway

  arklet-resolver:
    platform: linux/amd64
    container_name: arklet_resolver
    restart: always
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./ark:/app/ark
      - ./ark_import:/app/ark_import
      - ./arklet:/app/arklet
    env_file:
      - .env
    environment:
      ARKLET_PORT: "8018"
      RESOLVER: "true"
    ports:
      - "127.0.0.1:8018:8018"
    networks:
      - gateway
    # labels:  # redirecting http to https and defining routers and using tcl certresolver
    #   - "traefik.enable=true"
    #   - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
    #   - "traefik.http.routers.arklet-resolver.entrypoints=web"
    #   - "traefik.http.routers.arklet-resolver.rule=Host(`pid.tbiadata.tw`)"
    #   - "traefik.http.routers.arklet-resolver.entrypoints=websecure"
    #   - "traefik.http.routers.arklet-resolver.tls.certresolver=myresolver"
  nginx-arklet:  # nginx to serve static files
    image: nginx:latest
    container_name: nginx-arklet
    restart: always
    volumes:
      - ./nginx/stag/stag.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arklet-resolver
    links:
      - arklet-resolver:arklet-resolver
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx-arklet.rule=Host(`pid.tbiadata.tw`) || Host(`minter.tbiadata.tw`)"
      - "traefik.http.routers.nginx-arklet.entrypoints=websecure"
      - "traefik.http.routers.nginx-arklet.tls.certresolver=myresolver"

volumes:
  postgres: