version: "3.7"

networks:
  gateway2:
    external: true

services:
  postgres:
    container_name: arklet_db
    image: postgres:14-alpine
    # env_file:
    #   # - ./docker/env.local
    #   - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5435:5432"
      # - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arklet
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  arklet-minter:
    platform: linux/amd64
    container_name: arklet_minter
    restart: always
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./ark:/app/ark
      - ./ark_import:/app/ark_import
      - ./arklet:/app/arklet
    env_file:
      # - ./docker/env.local
      - .env
    environment:
      ARKLET_PORT: "8017"
      # ARKLET_PORT: "8001"
    expose:
      - 8017
      # ports:
      #   - "8017:8017"
      # - "8001:8001"

  arklet-resolver:
    platform: linux/amd64
    container_name: arklet_resolver
    restart: always
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    command: /app/entrypoint.sh
    volumes:
      - ./ark:/app/ark
      - ./ark_import:/app/ark_import
      - ./arklet:/app/arklet
    env_file:
      # - ./docker/env.local
      - .env
    environment:
      # ARKLET_PORT: "8000"
      ARKLET_PORT: "8018"
      RESOLVER: "true"
    expose:
      - 8018
    # ports:
    #   - "8018:8018"
      # - "8000:8000"
    networks:
      # - internal
      - gateway2
    labels:  # redirecting http to https and defining routers and using tcl certresolver
      - "traefik.enable=true"
      # - "traefik.docker.network: gateway2"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.arklet-resolver.entrypoints=arklet-resolver"
      # - "traefik.http.routers.admin.rule=Host(`mk.getalice.ai`)"
      # - "traefik.http.routers.admin.middlewares=redirect-https@docker"
      - "traefik.http.routers.arklet-resolver.rule=Host(`pid.tbiadata.tw`)"
      - "traefik.http.routers.arklet-resolver.entrypoints=websecure"
      - "traefik.http.routers.arklet-resolver.tls.certresolver=myresolver"
  nginx-arklet:  # nginx to serve static files
    image: nginx:latest
    container_name: nginx-arklet
    restart: always
    volumes:
      - ./nginx/stag/stag.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arklet-resolver
    links:
      - arklet-resolver:arklet-resolver
    networks:
      - gateway2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-arklet.rule=Host(`pid.tbiadata.tw`)"
      - "traefik.http.routers.nginx-arklet.entrypoints=websecure"
      - "traefik.http.routers.nginx-arklet.tls.certresolver=myresolver"

volumes:
  postgres:
